/* This file is from "the internet", well I've combined 3 different versions over time.
 * Many things have been commented out since they're not needed for this project
 * and might need a bunch of other header files.
 * Things not included with the project should be available be default in Theos (namely ControlCenterUIKit).
 * Blanxd.H
 */

/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, September 20, 2017 at 10:02:12 PM Eastern European Summer Time
* Operating System: Version 11.0 (Build 15A372)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 8, 2019 at 1:25:48 PM Eastern European Standard Time
* Operating System: Version 12.1 (Build 16B92)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

/*
* This header is generated by classdump-dyld 1.0
* on Sunday, November 10, 2019 at 11:16:35 PM Eastern European Standard Time
* Operating System: Version 13.1.3 (Build 17A878)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUIKit/CCUIButtonModuleViewController.h>
//#import <ControlCenterUIKit/CCUIContentModuleContentViewController.h>
#import <ControlCenterUIKit/CCUIContentModuleContentViewController-Protocol.h>
//#import <ControlCenterUIKit/CCUIToggleModule.h>

@class UIImageView, UIImage, UIColor, CCUICAPackageDescription, NSString, CCUIToggleModule;
//, UIViewPropertyAnimator; // 13

@interface CCUIToggleViewController : CCUIButtonModuleViewController <CCUIContentModuleContentViewController> {
	UIImageView* _glyphImageView;
	UIImage* _glyphImage;
	UIImage* _selectedGlyphImage;
	UIColor* _selectedColor;
	CCUICAPackageDescription* _glyphPackageDescription;
	NSString* _glyphState;
	CCUIToggleModule* _module;
}
@property (assign,nonatomic) CCUIToggleModule* module;                   //@synthesize module=_module - In the implementation block
//@property (assign,nonatomic,__weak) CCUIToggleModule * module;                              //@synthesize module=_module - In the implementation block
//@property (readonly) unsigned long hash; // 11
//@property (readonly) unsigned long long hash; // 12,13
//@property (readonly) Class superclass; 
//@property (copy,readonly) NSString * description; 
//@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) double preferredExpandedContentHeight; 
@property (nonatomic,readonly) double preferredExpandedContentWidth; 
@property (nonatomic,readonly) double preferredExpandedContinuousCornerRadius; // 13
@property (nonatomic,readonly) BOOL providesOwnPlatter; 
//@property (nonatomic,readonly) UIViewPropertyAnimator * customAnimator; // 13
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)refreshState;
-(BOOL)_canShowWhileLocked; // 13
//-(id)module; // 11
-(CCUIToggleModule *)module;
//-(void)setModule:(id)arg1 ; // 11
-(void)setModule:(CCUIToggleModule *)arg1 ;
-(void)buttonTapped:(id)arg1 forEvent:(id)arg2 ;
-(double)preferredExpandedContentHeight;
-(BOOL)shouldFinishTransitionToExpandedContentModule;
-(void)reconfigureView;
@end
